### ISSUE TITLE
SauceLabs Titles For Tests  Not Showing Up

### ISSUE THREAD

**Issue by mattc41190** [webdriverio/wdio-jasmine-framework#11]
When running WDIO tests in SauceLabs only the names of the `it` functions are appearing. Other than this the test is listed as Jasmine TopLevel Suite. The WDIO [documentation](http://webdriver.io/guide/services/sauce.html) for this functionality uses Cucumber as the example and it clearly displays the name of both the `feature` and `scenario`. 

![jasminewdiobug01](https://cloud.githubusercontent.com/assets/8837616/15723729/7a89579a-2809-11e6-8487-9f35071b1a42.png)

**Comment by christian-bromann** [comment]
@mattc41190 so how should it be? Can you give an example?

**Comment by mattc41190** [comment]
http://webdriver.io/guide/services/sauce.html

The linked page shows the Cucumber equivalent to what I'd like to see. In Jasmine and Mocha you have `describe` and `it` blocks. Cucumber has `feature` and `scenario`. Feature and scenario say the correct data in Cucumber. In Jasmine only the `it` functions/blocks are named, but the `describe` blocks get a generic JasmineTopLevelSuite title.

**Comment by mattc41190** [comment]
If at any point you set the name in the browser caps then it takes that name.

**Comment by mattc41190** [comment]
Did any of that make sense?

**Comment by christian-bromann** [comment]
So you are saying that it would be nice to set the context also if we enter a suite (describe block)?

**Comment by mattc41190** [comment]
Precisely, seems like as though that would be the logical intent.

**Comment by christian-bromann** [comment]
This is fixed with the latest wdio-sauce-service version.
