### ISSUE TITLE
Possible to Publish New Version?

### ISSUE THREAD

**Issue by phil-lgr** [webdriverio/wdio-jasmine-framework#117]
There has been some fixes:

https://github.com/webdriverio/wdio-jasmine-framework/compare/v0.3.2...master

I guess we could bump to v0.4.0?

**Comment by christian-bromann** [comment]
@phil-lgr integration tests are still failing and it looks like a legit issue, can't test before this is fixed.

**Comment by phil-lgr** [comment]
My bad, didn't realize that. I have a sick day so I will have a look

**Comment by phil-lgr** [comment]
This is one of the 2 test failling

```
describe('hook exceptions', () => {
        it('should fail test', async () => {
            global.browser = new WebdriverIO()
            global.browser.options = { sync: false }
            const adapter = new JasmineAdapter(0, {}, failureSpec, {})
            const result = await adapter.run()
            result.should.be.equal(1, 'test should fail')
            adapter.reporter.getFailedCount().should.be.equal(1, 'test should fail')
        })
    })
``` 

Looks like the failed tests are not counted somehow.. digging down

**Comment by phil-lgr** [comment]
![image](https://user-images.githubusercontent.com/9644867/37979292-3f16a880-31b6-11e8-9cb3-b88b3652af5d.png)

Does it ring a bell? Test is failing but status is "passed"

**Comment by phil-lgr** [comment]
![image](https://user-images.githubusercontent.com/9644867/37979753-68cbc204-31b7-11e8-8211-06597dcf22e6.png)

failedExpectations is 0 in the reporter but debugging inside jasmine I see the failedExpectations having one item, somehow we don't it on `test`

**Comment by phil-lgr** [comment]
The error is added on the result:

![image](https://user-images.githubusercontent.com/9644867/37980141-677b48ec-31b8-11e8-9edd-090a947312fd.png)

**Comment by phil-lgr** [comment]
https://github.com/jasmine/jasmine/issues/1409#issuecomment-360858185 looks like:

>We have however done some work to make all errors at the suite level report the same way (on the suite) instead of either making a spec you've never heard of, or cascading the failure down to the children.

So I guess we could look at the suite instead of looking at the spec for failedExpectations? Mmmm

**Comment by phil-lgr** [comment]
![image](https://user-images.githubusercontent.com/9644867/37981792-9ea6f1be-31bc-11e8-813f-8747d02e057b.png)

Trying to see if it impacts anything else... I guess we'll have to change tests.retry.* they check for number of errors on beforeAll hooks

**Comment by phil-lgr** [comment]
See pull #118
