### ISSUE TITLE
Session not ended after exceptions thrown

### ISSUE THREAD

**Issue by patthiel** [webdriverio/wdio-jasmine-framework#12]
## The problem

When a waitFor command or waitUntil times out, it throws an exception like below.. However, after this error is encountered, the runner fails to end the session where the error was encountered. Leaving many dead browsers open, when running a full suite of integration tests.
```
/Developer/myProject/node_modules/wdio-jasmine-framework/node_modules/wdio-sync/node_modules/fibers/future.js:313
						throw(ex);
						^
Error: element (something) still not existing after 5000ms
```

## Environment

* WebdriverIO version: 4.0.9
* Node.js version: 4.2.4
* wdio test runner
* synchronous & asynchronous modes
* gulp-webdriver
* selenium-standalone 2.5.3  (occurs in both FF driver & Chromedriver 2.22)

## Link to Selenium/WebdriverIO logs

[Selenium Logs](https://gist.github.com/patthiel/b9214fd287106dfe003aee8f6506d42a)
[Wdio Logs](https://gist.github.com/patthiel/bd09ad742a02f67cee7ec8db042e56c3)

## Code To Reproduce Issue

[Example Spec](https://gist.github.com/patthiel/335960936ce50ca560503b542cfabf1c)

@christian-bromann i don't think this is happening with each framework, so i'm posting it here as a jasmine specific bug. Let me know if you think this is more a wdio bug and i can close this and open it in that project

**Comment by mattc41190** [comment]
+1

Also happens to me. I have not looked into whether or not the same issue occurs in Mocha or Cucumber implementations.

**Comment by lrobanthro** [comment]
+1 waitUntil is one of those vital commands that allows testers to avoided the dreaded browser.pause!

**Comment by christian-bromann** [comment]
I will look at it asap

**Comment by christian-bromann** [comment]
@patthiel could you retry with the recent published version?

**Comment by patthiel** [comment]
This works as expected now! 🎉
