### ISSUE TITLE
Cannot write asynchronous tests (sync: false) with jasmine

### ISSUE THREAD

**Issue by kurtharriger** [webdriverio/wdio-jasmine-framework#13]
We are considering switching from `sync: true` to `sync: false` in `wdio.conf` and using the new ES 7 async/await syntax instead of fibers, but we cannot get jasmine to work with `sync: false`. 

We have found fibers to sometimes cause confusion to devs not yet familiar with what fibers are actually doing and how they work.  They also require adding commands to browser for async actions like setting up drymock that has nothing to do with browser.  

My understanding is that if a test returned a promise that it would wait.  This appears to be natively supported by `mocha`, but this does not seem to be natively supported by `jasmine`.  In other projects we are using [jasmine-pit](https://www.npmjs.com/package/jasmine-pit) to add support for promises (and the async/await syntax).  

The [wdio-sync](https://github.com/webdriverio/wdio-sync) project assumes the specFn takes no arguments [here](https://github.com/webdriverio/wdio-sync/blob/master/index.js#L477) and thus swallows the done function object provided by jasmine and required by plugins such as [jasmine-pit](https://www.npmjs.com/package/jasmine-pit).   

Additionally wdio-jasmine-framework only supports test methods named 'it' or 'fit' [here](https://github.com/webdriverio/wdio-jasmine-framework/blob/master/lib/adapter.js#L61) so a plugin like  [jasmine-pit](https://www.npmjs.com/package/jasmine-pit) would not work anyway.

I created a test project [webdriverio-async-jasmine-tests](https://github.com/kurtharriger/webdriverio-async-jasmine-tests) with some very simple specs that don't behave as expected.

I created two async style tests with `sync:false` configured in wdio.conf.  One of which expects done argument which is not provided and the other which returns a promise.  

Interestingly, wdio does appear to wait for the promise in `beforeAll`, but it does not wait for promise returned from `it`.  I'm not entirely certain why promises work in `beforeAll` but not in `it` as they seem to use mostly the same code.  It would be awsome if wdio-jasmine-framework would resolve promises returned from the `it` block because then the async/await syntax should just work.  

Is it feasible to have promises returned by `it` block auto resolved by wdio? or does this require changes to jasmine itself?  
If jasmine changes would be needed how about supporting the `pit` method to resolve promises?

[webdriverio-async-jasmine-tests](https://github.com/kurtharriger/webdriverio-async-jasmine-tests)

**Comment by kurtharriger** [comment]
So I in part figured out why done is being swallowed as jasmine only passes the done argument if the function argument length is 1.  Possible fix here: 

https://github.com/webdriverio/wdio-sync/compare/master...kurtharriger:jasmine?expand=1

I'm still uncertain why in my example returning a promise does not work.  I found there does appear to be a test for async behavior [here](https://github.com/webdriverio/wdio-jasmine-framework/blob/master/test/tests.spec.js#L61).  
In my case tests that are suppose to fail never fail because the expectation isn't evaluated so I tried to amend the test to verify that tests fail when they are supposed to [here](https://github.com/webdriverio/wdio-jasmine-framework/compare/master...kurtharriger:test-fail).  This does pass however and I can't see what it is that I'm doing differently in my example which does not work (passes when it should fail)  [here](https://github.com/kurtharriger/webdriverio-async-jasmine-tests/blob/master/test/specs/async/promise.spec.js#L12)

**Comment by christian-bromann** [comment]
If you run your tests asynchronous with jasmine, the it function should respect promises.

**Comment by kurtharriger** [comment]
That's not the behavior I'm seeing in my example. I could be doing something wrong, but it's not obvious why the following test does not have the expected behavior.  

This test should fail but it passes because the `expect(false).toBe(true)` is never run:
https://github.com/kurtharriger/webdriverio-async-jasmine-tests/blob/master/test/specs/async/promise.spec.js#L12
