### ISSUE TITLE
Retry Flaky Tests Does Not Work

### ISSUE THREAD

**Issue by juliosantanaiii** [webdriverio/wdio-jasmine-framework#16]
Documentation suggests that recent versions of wdio-jasmine-framework allow for [retries of flaky tests](http://webdriver.io/guide/testrunner/retry.html).

The most recent available version of wdio-jasmine-framework in `node` is 0.2.5, and the documentation states that this functionality is available in 0.3.0 or greater (unavailable?  mistake in documentation?).

Anyway, there are tests in release 0.2.5 for the retry functionality, but the retries do not work on the tests I am running.

**Comment by christian-bromann** [comment]
Are you running WebdriverIO with latest version too?

**Comment by juliosantanaiii** [comment]
4.2.3

**Comment by juliosantanaiii** [comment]
Any thoughts?  We have the `sync` flag set to false.

**Comment by christian-bromann** [comment]
Not reproducible, I have latest version with
__wdio.conf.js__
```js
exports.config = {
    specs: ['./a.js'],
    capabilities: [{
        browserName: 'phantomjs'
    }],
    framework: 'jasmine'
}
```
__a.js__
```js
describe('a', function () {
    it('b', function () {
        console.log('run me')
        throw new Error('fail')
    }, 2)
})
```
getting:
```
./bin/wdio wdio.conf.js

run me
run me
run me
F

0 passing (3.00s)
1 failing

1) a b:
Failed: fail
running phantomjs
Error: fail
    at /Users/christianbromann/Sites/Webprojekte/webdriverjs/DEV/a.js:4:15
```
as you can see the spec ran 3 times.

**Comment by juliosantanaiii** [comment]
@christian-bromann, your example is not asynchronous.  How does this address my problem statement?
