### ISSUE TITLE
Asynchronous Retry Flaky Tests Does Not Work

### ISSUE THREAD

**Issue by juliosantanaiii** [webdriverio/wdio-jasmine-framework#18]
I opened issue #16 , but it was closed.  The resolution for issue #16 provides a synchronous example.  My use case is while using async/await functionality and with the `sync` flag to false.

**Comment by christian-bromann** [comment]
@juliosantanaiii the example should also work for async code. Please update your adapter and try again. If it is still not working please provide an example to reproduce and I am happy to reopen the issue.
