### ISSUE TITLE
Update jasmine dependency to most recent version (2.5.2)

### ISSUE THREAD

**Issue by delijah** [webdriverio/wdio-jasmine-framework#19]
...and pass on the stopSpecOnExpectationFailure config option.

Related issue: https://github.com/webdriverio/webdriverio/issues/1654#issuecomment-255060507

**Comment by delijah** [comment]
Any news on this?

**Comment by christian-bromann** [comment]
I am literally working on this right now :-P

**Comment by delijah** [comment]
Haha, cool :)

**Comment by delijah** [comment]
I see, jasmine version has been changed to 2.5.2. Thanks!

I am just curious if the stopSpecOnExpectationFailure config option will be passed to the jasmine core. If i analyse the wdio-jasmine-framework code, it looks like it does not pass on the stopSpecOnExpectationFailure config option.

**Comment by christian-bromann** [comment]
@delijah `stopSpecOnExpectationFailure` is not really applicable when running Jasmine with WebdriverIO. With the new version `4.5.0` (not released yet) you can bail and stop the wdio test runner from executing more tests.
