### ISSUE TITLE
Jasmine Capture screen on failure even jasmineNodeOpts hasn't been set

### ISSUE THREAD

**Issue by TuHuynhVan** [webdriverio/wdio-jasmine-framework#26]
First at all, thank @christian-bromann and the team so much for bringing us an awsome JS framework.

I just started using webdriverio, I used wdio as a test runner and Jasmine framework. Sorry if it's a dummy question if I missed any info from documentation (Developer Guide).

I saw that to capture a failure, we need to add:
<img width="697" alt="screen shot 2016-12-22 at 11 46 47" src="https://cloud.githubusercontent.com/assets/18535553/21415478/d83a565e-c83c-11e6-9008-029b3af9f2b9.png">

But in my wdio.conf.js. I didn't set that but I'm still getting screeenshot on failure. That's cool but I don't now why.

<img width="802" alt="screen shot 2016-12-22 at 11 52 06" src="https://cloud.githubusercontent.com/assets/18535553/21415503/1b58d028-c83d-11e6-84c1-33ac6629a234.png">

Thanks!

**Comment by christian-bromann** [comment]
> for bringing us an awsome JS framework.

Thanks 😊 

Make sure you have [screenshotOnReject](https://github.com/webdriverio/webdriverio/blob/055ab6257678b8f9ff3d33d610b75ce4676335e9/docs/guide/getstarted/configuration.md#screenshotonreject) set to false. Feel free to join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions 😉 .
