### ISSUE TITLE
Avoid requiring node-fibers when sync == false

### ISSUE THREAD

**Issue by normanrz** [webdriverio/wdio-jasmine-framework#27]
We enjoy using jasmine with WebdriverIO. We prefer to use async/await over the synchronous code with node-fibers and therefore have set `sync: false` in our config. With the change to node 7 we had issues with `node-fibers` binding not being compatible. I looked through some issues and found that others had problems with fibers as well.

Would it be possible to avoid requiring `node-fibers` (or `wdio-sync`) if synchronous mode is disabled anyways? I understand that it needs to be in the dependencies, but I imagine it wouldn't need to be required.

I am happy to provide a PR if you think this is a good idea. Any pointers to code are appreciated. Thanks!

**Comment by christian-bromann** [comment]
> Would it be possible to avoid requiring node-fibers (or wdio-sync)

Not without making the installation process more difficult. wdio-sync is used by most of the people who use webdriverio's testrunner. Telling them to additional install fibers would make the installation more confusing. I recommend to fork this project and remove the dependency if you have problems with fibers. Thanks for understanding.

**Comment by normanrz** [comment]
Thanks for your feedback. I wasn't suggesting to drop fibers as a dependency. For my use case it would be sufficient to just not do the `require(...)` call.

**Comment by christian-bromann** [comment]
If you set `async: false` we don't execute any fiber method. What happens when the package requires fibers?

**Comment by normanrz** [comment]
The `fibers` package had some problems compiling correctly with recent node.js versions on both Mac and Linux. Therefore, it would crash the whole process. I suspect this will become an issue again, once new node.js versions are released.

**Comment by christian-bromann** [comment]
The guy behind fibers is actively working on making it compatible with latest node versions. I have no issues using Mac with Node v7.4.0 (besides some deprecation warnings)
