### ISSUE TITLE
Is the Jasmine `done` callback supposed to work?

### ISSUE THREAD

**Issue by adborden** [webdriverio/wdio-jasmine-framework#28]
I'm trying to write an async spec using Jasmine's `done` callback, but it complains that `done` is undefined. This works find with Jasmine 2.5.2 without the wdio wrapper.

```javascript
describe('jasmine async', function () {
  it('works with a done callback', function (done) {
    setTimeout(function () {
      done.fail();
    }, 10);
  });
});
```

Which results in

```
․/home/adborden/projects/cg/new/973ade9632c4629c753422755ddacafe-106fc7d391d5f1d75bf190fa1023197320d39d6d/spec.js:5
      done.fail();
          ^

TypeError: Cannot read property 'fail' of undefined
    at Timeout._onTimeout (/home/adborden/projects/cg/new/973ade9632c4629c753422755ddacafe-106fc7d391d5f1d75bf190fa1023197320d39d6d/spec.js:5:11)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)


1 passing (2.80s)


npm ERR! Test failed.  See above for more details.
```

But I would expect to see 1 failure.

I tried to setup a minimal example to demonstrate this in case there's something wrong with my setup. You can try this out locally by downloading [this gist](https://gist.github.com/adborden/973ade9632c4629c753422755ddacafe), unpack, and run `npm install && npm test`.

**Comment by frickjack** [comment]
I believe you need to specify 'done' as an argument to your callback.

describe('jasmine async', function (done) {
  it('works with a done callback', function (done) {
    setTimeout(function () {
      done.fail();
    }, 10);
  });
});

**Comment by christian-bromann** [comment]
@adborden the done callback is not supported. WebdriverIO runs commands synchronously. No need for done calls.

**Comment by adborden** [comment]
The reason I need it is for the initial test setup, which I feel is a valid use case despite using WebdriverIO. As part of my test setup I need to start my sever `hapi.start(cb)` which is an async call, nothing to do with WebdriverIO.

Maybe I'm missing the use case for this wrapper, but it seems strange that the Jasmine wrapper actually removes Jasmine functionality. If I configure WebdriverIO to run `sync: false`, I still don't get `done` callbacks?

Is there a way to use Jasmine async with WebdriverIO?

**Comment by christian-bromann** [comment]
@adborden use the call command to synchronize async calls, e.g.
```js
browser.call(() => new Promise((resolve, reject) => hapi.start((err, result) => {
    if (err) {
        return reject(err);
    }
    resolve(result);
})
```

**Comment by adborden** [comment]
Ah ha, thank you! I also found that returning a promise to Jasmine still works as expected, is that unspecified behavior for `wdio-jasmine-framework`?

```javascript
it('fails', function () {
  return new Promise(function (resolve, reject) {
    setTimeout(function () {
      reject('foo');
    }, 10);
  });
});

// Failed: foo
```

**Comment by christian-bromann** [comment]
> is that unspecified behavior

Nope, this is correct according to jasmine documentation
