### ISSUE TITLE
Does not display each expect result

### ISSUE THREAD

**Issue by kariasbolster** [webdriverio/wdio-jasmine-framework#47]
Hi, I have an it that contains multiple expects and when one of them fails, I can't determine which one because in the command line it will only display one error for the whole it block so i need to manually check which of the expects failed. Is there a way to display all the failed in expects?

**Comment by christian-bromann** [comment]
@kariasbolster if an expect assertion fails it throws an exception, so nothing is executed after this. You need to assert both value in one assertion.

> Is there a way to display all the failed in expects?

The stack trace should show you which failed. Also you can have a specific assertion text that explains what fails. Check chai API for that. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
