### ISSUE TITLE
afterEach does not consider `done` argument

### ISSUE THREAD

**Issue by jahtalab** [webdriverio/wdio-jasmine-framework#54]
Using `afterEach` like this:
```
  afterEach(function (done) {
  })
```

Should fail the test because `done` is never called, but it passes.

**Comment by christian-bromann** [comment]
@jahtalab wdio testrunner doesn't support this. All commands are synchronous anyway. No need for such callbacks.

**Comment by jahtalab** [comment]
@christian-bromann ,
Thanks for your response.
So there's no way to make async calls in the `afterEach`?

**Comment by jahtalab** [comment]
Also, I have `sync: false` in my wdio config.
Doesn't that suppose to disable synchronous feature?

**Comment by christian-bromann** [comment]
> So there's no way to make async calls in the afterEach?

It sure is, just return a promise. Mocha will wait until the promise is resolved.

> Doesn't that suppose to disable synchronous feature?

Yup it does. However you still don't need the callback as you just can return a promise. Using the `done` callback is an outdated pattern from times where promises hasn't been invented.

**Comment by jahtalab** [comment]
Great! Thanks @christian-bromann!

**Comment by jahtalab** [comment]
@christian-bromann , A follow up on this. is there anyway to throw an exception (or log a warning) if the function does not return a promise?

Right now all of the tests that are using the callback pattern are passing simply because they're not returning a promise.
