### ISSUE TITLE
The expectationResultHandler function affect failed test

### ISSUE THREAD

**Issue by mjancarik** [webdriverio/wdio-jasmine-framework#7]
I use [wdio example](https://github.com/webdriverio/webdriverio/tree/master/examples/wdio) for jasmine. I made two changes. I defined expectationResultHandler function for taking [screenshot](http://webdriver.io/guide/testrunner/frameworks.html#Intercept_Assertion) and failed test from example where I changed title. I got result only 0 passing and random I got right result 0 passing, 1 failing.

I think there is problem with this line of code:
`
browser.saveScreenshot(('assertionError_' + title + '.png'));
`

**Comment by christian-bromann** [comment]
Sorry for the late response. Fixed example:
```js
jasmineNodeOpts: {
    defaultTimeoutInterval: 10000,
    expectationResultHandler: function(passed, assertion) {
        /**
         * only take screenshot if assertion failed
         */
        if(passed) {
            return;
        }

        browser.saveScreenshot('assertionError_' + assertion.error.message + '.png');
    }
},
```

**Comment by mjancarik** [comment]
Thank you Christian..
