### ISSUE TITLE
tests cannot execute async code

### ISSUE THREAD

**Issue by slysenko** [webdriverio/wdio-jasmine-framework#70]
Async code (https request) is not executed within the test.

>Steps:

code:

```
var http = require("https");
...

function api_request(options, to_write) {
  return new Promise(resolve => {
    var req = http.request(options, function(res) {
      var chunks = [];
      var cookies = res.headers['set-cookie'];

      res.on("data", function(chunk) {
        chunks.push(chunk);
      });
      res.on("end", function() {
        var body = Buffer.concat(chunks).toString();
        if (!isValidJSON(body)) {
          body = "{}";
        }
        resolve({ body: JSON.parse(body), cookies: cookies });
      });
    });

    if (options.method == "POST") {
      req.write(JSON.stringify(to_write));
    }
    req.end();
  });
}
describe('test', function() {
  beforeAll(function(done) {
    api_request(login_options, login_to_write).then(function(data) {
      var session_options = {
        "method": "GET",
        ...
      };
      return api_request(session_options);
    }).then(function(data) {
      var profile_show_options = {
        "method": "GET",
        ...
      };
      token = data.body.token;
      return token;
    }).then(function(data) {
      var profile_update_options = {
        "method": "POST",
        ...
      };
      var profile_update_to_write = {
        name: 'FirstName LastName',
        ...
      };
      return api_request(profile_update_options, profile_update_to_write);
    }).then(function(data) {
      done();
    });
  });
```
This code perfectly works (i.e. it successfully logs in to server, gets necessary data, then updates the required fields) in a separate .js file when run from node as 
`node test.js`  

This code also perfectly works if it is run within a standalone jasmine as 
`jasmine ./test.js`

However it seems like this code is totally skipped when executed using wdio as:
`./node_modules/.bin/wdio ./my/autotest/wdio.conf.test.js --spec ./my/autotest/specs/test.js`

>Setup:

"wdio-jasmine-framework": "^0.3.2",
"wdio-selenium-standalone-service": "0.0.9",
"jasmine": "~2.8.0",

**Comment by christian-bromann** [comment]
in wdio if you run async code use the [`call`](http://webdriver.io/api/utility/call.html#Usage) command. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
