### ISSUE TITLE
Fix `grep` and `invertGrep` documentation

### ISSUE THREAD

**Issue by antkazam** [webdriverio/wdio-jasmine-framework#72]
In the README.

`grep` is said to take a `String[]` value, but in `adapter.js` it appears to expect grep to be a string version of a RegExp. https://github.com/webdriverio/wdio-jasmine-framework/blob/master/lib/adapter.js#L210

`invertGrep` is said to take a `String[]` value. This seems to be a copy & paste error. invertGrep is a boolean option.

**Comment by christian-bromann** [comment]
@antkazam can you make a PR with required changes?

**Comment by antkazam** [comment]
@christian-bromann  please take a look at https://github.com/webdriverio/wdio-jasmine-framework/pull/73

**Comment by christian-bromann** [comment]
Ok, let's continue convo in #73
