### ISSUE TITLE
browser.debug() times out 

### ISSUE THREAD

**Issue by kurtharriger** [webdriverio/wdio-jasmine-framework#9]
In theory you should be able to call brower.debug() to manually inspect the browser state continue when you are ready by pressing enter at the console.
http://webdriver.io/api/utility/debug.html

I get that async tests shouldn't wait forever, but it would be nice if there was a way to disable this automatic timeout when debugging.

**Comment by patthiel** [comment]
Thinking about this issue.. When running tests via WDIO test runner, the jasmine timeout is controlled via by the wdio.conf.js file in
```
jasmineNodeOpts: {
        // Jasmine default timeout
        defaultTimeoutInterval: timeoutHere
} 
```

I don't know if there's an easy way for this timeout to get ignored when calling `browser.debug()`... Instead, i'd suggest just changing the default timeout to something like 60000 * 60  when debugging.. 

As a best practice, you may want to set up a separate `debug.wdio.conf.js` with custom options like this that you ultimately will not want as your standard wdio configuration.

**Comment by christian-bromann** [comment]
@patthiel thanks for your comment. @kurtharriger please increase the default timeout as @patthiel suggested
