### ISSUE TITLE
"test.passed" is undefined in "afterTest" Hook

### ISSUE THREAD

**Issue by phil-lgr** [webdriverio/wdio-jasmine-framework#97]
I am trying to add an `afterTest` hook in my wdio config file, but the test.passed is always undefined.

So I put a breakpoint here: https://github.com/webdriverio/wdio-jasmine-framework/blob/master/lib/adapter.js#L183

```
if (params.payload.type && params.payload.type === 'test') {
    message.parent = this.lastSpec.description
    message.passed = params.payload.failedExpectations.length === 0
}
```

and I noticed that the `params.payload.type` was never 'test':

![image](https://user-images.githubusercontent.com/9644867/36704542-c84c6764-1b2e-11e8-9efc-d739421c8fe3.png)

I believe that this check needs to be updated, maybe something changed in jasmine? Not sure.

package.json:

```
 "wdio": "1.0.3",
    "wdio-browserstack-service": "0.1.14",
    "wdio-dot-reporter": "0.0.9",
    "wdio-jasmine-framework": "0.3.2",
    "wdio-junit-reporter": "0.3.1",
    "wdio-selenium-standalone-service": "0.0.9",
```

**Comment by carlos-gva** [comment]
@phil-lgr @christian-bromann 
I also detected this issue today and after some investigation, it seems that some Jasmine change is causing it.

The issue starts when you install Jasmine v2.9.0 or later, so something happened between v2.8.0 and 2.9.0...

So, my temporary solution was to force on my package-lock.json the v2.5.3 of wdio-jasmine-framework Jasmine dependency.

Cheers.

**Comment by christian-bromann** [comment]
Thanks for bringing this up! Will look into it. If anyone can beat me to it gets a free beer 😉

**Comment by markbrouch** [comment]
Same issue, I believe this is affecting https://github.com/webdriverio/wdio-sauce-service/issues/49

**Comment by RTsGIT** [comment]
Still facing the same issue. As `wdio-jasmine-framework` is not released after the fix is merged.
